---
layout: post
title: "Life tables: brief introduction"
description: ""
category: demography
tags: [prelim, R, home]
---

A _life table_ is just one way of summarizing a cohort's mortality experience. Below a simple way to build a life table using R.

```{r, echo=FALSE}
options(replace.assign=TRUE, tidy=TRUE, width=60, scipen = 4, digits = 3)
```

```{r}
dat  <- read.csv("frmales85.csv", sep=",", header=T)
# length of intervals
dat$n   <- c(diff(dat$x),NA)
# number of intervals
max <- length(dat$x)
# age 85 is an open interval
dat
```

```{r}
# age-specific mortality rates assuming $_nM_x=_nm_x$
dat$nmx  <- dat$nDx/dat$nNx
# age-specific probability to die
dat$nqx  <- (dat$n*dat$nmx)/(1+(dat$n-dat$nax)*dat$nmx)
dat$nqx[max]  <- 1
dat$npx  <- 1-dat$nqx
```

```{r}
# definition of radix
radix  <- 100000
# easy way to get lx without a loop
dat$lx <- radix * c(1, cumprod(dat[1:max-1,"npx"]))
dat$ndx <- dat$lx * dat$nqx
dat[, c(-2,-3)]
```

```{r}
# Lx for the open interval
dat$nLx  <- dat$lx * dat$n - (dat$n-dat$nax)*dat$ndx
dat$nLx[max] <-  dat$lx[max]/dat$nmx[max]
```

```{r}
dat$Tx <- rev(cumsum(rev(dat$nLx)))
dat$ex <- dat$Tx/dat$lx
dat[, c(-2:-6)]
```