---
layout: post
title: "Population Momentum"
description: 
category: demography
tags: [prelim, R, home]
---
{% include JB/setup %}

In this example I discuss some characteristics of the population momentum, using data from China (1990). Let's take a look at the data first:  

```{r echo=FALSE} 
options(replace.assign=TRUE, tidy=TRUE, width=90, scipen =4, digits = 3)
setwd("/Users/sdaza/Dropbox/sdaza.github.com/Rmd/")
```

```{r echo=TRUE}

age <- seq(0, 100, 5)
fm <- c(rep(0,3), .003, .078, .065, .024, .006, .001, .001, rep(0, 11))
L <- c(4.76, 4.72, 4.71, 4.69, 4.67, 4.64, 4.6, 4.56, 4.5, 4.41, 4.29, 4.11, 3.86, 3.48,
	2.92, 2.18, 1.34, 0.62, .17, .03, .004)
N <- c(60, 50, 47, 59, 62, 51, 40, 42, 30, 23, 22, 20, 16, 13, 10, 6, 3, 1, .2, .04, .005)
dat <- data.frame(age, N, fm, L)

```


```{r echo=FALSE}

dat

```



```{r echo=TRUE}

pr <- N/sum(N)
nrr <- sum(fm*L)

```


```{r echo=TRUE}

S <- NA
for (i in 1:20) {
	S[i] <- L[i+1]/L[i]
}

```

```{r echo=TRUE}

S[20] <- L[21]/(L[20]+ L[21])

F <- NA
for (i in 1:21) {
	F[i] <- L[1]/2 * sum(fm[i+1]*S[i], fm[i], na.rm=TRUE)
}

```


```{r echo=TRUE}

M <- matrix(0, 21, 21)
M[1, 1:21] <- F

```

```{r echo=TRUE}

D <- diag(20)
D <- diag(20)*S

M[2:21, 1:20] <- D
M[21,21] <- S[20]

mp <- function(mat,pow) {
	ans <- mat
	for (i in 1:(pow-1)) {
		ans <- mat%*%ans
	}
	return(ans)
}


e <- eigen(M)


max(abs(e$values)) 
(max(abs(e$values)) - 1)/5

ev <- as.numeric(e$vectors[,1])
spr <- ev/sum(ev)
cspr <- cumsum(spr)
mst <- 35 + (.5-cspr[8])/spr[9]*5

pr <- N/sum(N)
cpr <- cumsum(pr)
mobs <- 15 + (.5-cpr[4])/pr[5]*5


M[1,] <-  M[1,]/nrr
sum(M[1,])

e <- eigen(M)
max(abs(e$values)) 

x <- mp(M,10000) %*% N
sum(x)

sum(x[13:21])/sum(N[13:21])

N2 <- N
N2[1:5] <- N2[1:5] + 10
N2

x <- mp(M,10000) %*% N2
sum(x[13:21])/sum(N2[13:21])

```

